server:
  port: 0

spring:
  application:
    name: cargo-transportation-jwt-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss:SSS} %X %-5p {%c} {%t} %m%n"

jwt:
  secretKey: ${jwt-secret-key}
  tokenLifetimeHours: ${jwt-token-lifetime}