server:
  port: 8081

spring:
  application:
    name: cargo-transportation-user-info-service
  datasource:
    url: jdbc:postgresql://localhost:5432/security?currentSchema=user_info
    username: tsavaph
    password: 1235
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss:SSS} %X %-5p {%c} {%t} %m%n"